### ISSUE TITLE
如何离线使用

### ISSUE THREAD

**Issue by toddlerya** [CMBill/lxgw-wenkai-screen-web#3]
您好，字体在cdn已经分包了，如果我想在没有互联网的环境下离线使用，有什么建议方案吗？

**Comment by toddlerya** [comment]
看了下  https://chinese-font.netlify.app/online-split/ 已经知道该怎么做了。

**Comment by bolechen** [comment]
npm install lxgw-wenkai-screen-web
安装到本地的话，可以直接引用 node_modules 中的文件嘛
试了下好像会报错

**Comment by CMBill** [comment]
> npm install lxgw-wenkai-screen-web 安装到本地的话，可以直接引用 node_modules 中的文件嘛 试了下好像会报错

直接npm到本地下载的文件应该和云端使用是一样的，不知道是什么样的报错呢

**Comment by bolechen** [comment]
> > npm install lxgw-wenkai-screen-web 安装到本地的话，可以直接引用 node_modules 中的文件嘛 试了下好像会报错
> 
> 直接npm到本地下载的文件应该和云端使用是一样的，不知道是什么样的报错呢

 抱歉，是我的使用方式有问题，我用的是 Next.js

之前在 global.css 中

```
@import "lxgw-wenkai-screen-web";
```

发现不行，在 layout.ts 中

```
import "lxgw-wenkai-screen-web";
```

是可以的。
